default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 
  host: localhost
  port: 5432

development:
  <<: *default
  database: corretudo_development

test:
  <<: *default
  database: corretudo_test

production:
  <<: *default
  database: corretudo_production